%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

Camera.k1: -0.28340811
Camera.k2: 0.07395907
Camera.p1: 0.00019359
Camera.p2: 1.76187114e-05
# Camera.k3: 0.0

# Camera frames per second 
Camera.fps: 20
#Camera.fps: 4.4

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# PNEC Parameters
#--------------------------------------------------------------------------------------------
PNEC.NEC: 0

PNEC.noiseFrame: "Target"
PNEC.regularization: 1.0e-13
PNEC.weightedIterations: 10

PNEC.SCF: 1
PNEC.ceres: 1

PNEC.ransac: 1
PNEC.maxRANSACIterations: 5000
PNEC.RANSACSampleSize: 10
